apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "woodpecker-agent.fullname" . }}
  labels:
    {{- include "woodpecker-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "woodpecker-agent.selectorLabels" . | nindent 6 }}
  replicas: 2
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "woodpecker-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      {{- if and (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) (.Values.topologySpreadConstraints) }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      volumes:
      - name: sock-dir
        emptyDir: {}
      {{- with .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}

      containers:
      - name: agent
        image: "{{ .Values.image.repository }}:{{ include "woodpecker-agent.imageTag" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ include "woodpecker-agent.fullname" . }}
        {{- range .Values.extraSecretNamesForEnvFrom }}
        - secretRef:
            name: {{ . }}
        {{- end }}
        volumeMounts:
        - name: sock-dir
          mountPath: /var/run
        {{- with .Values.extraVolumeMounts }}
          {{ toYaml . | nindent 8 }}
        {{- end }}

      - name: dind
        image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
        securityContext:
          {{- toYaml .Values.sidecar.securityContext | nindent 10 }}
        env:
        - name: DOCKER_DRIVER
          value: overlay2
        envFrom:
        - configMapRef:
            name: {{ include "woodpecker-agent.fullname" . }}
        {{- range .Values.extraSecretNamesForEnvFrom }}
        - secretRef:
            name: {{ . }}
        {{- end }}
        resources:
          {{- toYaml .Values.sidecar.resources | nindent 10 }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: sock-dir
          mountPath: /var/run
        {{- with .Values.sidecar.extraVolumeMounts }}
          {{ toYaml . | nindent 8 }}
        {{- end }}
