# Specs for CronJob resources to create
CronJobs: []
  # - name: "example"
  #   schedule: '"@daily"'
  #   uid: "1000"
  #   gid: "1000"
  #   ignore_errors: false
  #   output_template: "%(title)s.%(ext)s"
  #   recode_video:
  #     enabled: true
  #     format: "mkv"
  #     # These are just ffmpeg encoder arguments
  #     args: "-c:a copy -c:v copy"
  #     keep_original: false
  #   geo_bypass_country: ""
  #   reject_title: ""
  #   other_args: []
  #   url: "https://youtube.com/"
  #   job_download_volume:
  #     hostPath:
  #       path: /home/me/Videos

# The global download_volume specification will be the default volume
# videos are saved to. It can be overidden on a per-job basis using
# the job_download_volume spec.
download_volume: {}

persistence:
  annotations: {}
  storageClass: ""