---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "woodpecker.fullname" . }}
  labels:
    {{- include "woodpecker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - protocol: TCP
      name: grpc
      port: 9000
      targetPort: 9000
  selector:
    {{- include "woodpecker.selectorLabels" . | nindent 4 }}
