{{- range .Values.CronJobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: youtube-dl
            env:
            - name: PUID
              value: {{ .uid | quote }}
            - name: PGID
              value: {{ .gid | quote }}
            resources:
              limits:
                cpu: 1
            image: mikenye/youtube-dl
            imagePullPolicy: IfNotPresent
            args:
            - -U
            {{- if .ignore_errors }}
            - --ignore-errors
            {{- end }}
            - --output
            - "/downloads/{{ .output_template | default "%(title)s.%(ext)s" }}"
            - --write-sub
            - --download-archive
            - /config/seen
            {{- if .recode_video.enabled }}
            - --recode-video
            - {{ .recode_video.format }}
            - --postprocessor-args {{ .recode_video.args }}
              {{- if .recode_video.keep_original }}
            - --keep-video
              {{- end }}
            {{- end }}
            {{- if .geo_bypass_country }}
            - --geo-bypass-country {{ .geo_bypass_country }}
            {{- end }}
            {{- if .reject_title }}
            - --reject-title {{ .reject_title }}
            {{- end }}
            {{- if .other_args }}
              {{- toYaml .other_args | nindent 12 }}
            {{- end }}
            - {{ .url }}
            - '> /downloads/lastrun.log 2>&1'
            volumeMounts:
              - mountPath: /config
                name: youtubedl-cron-config
              {{- range .additionalVolumeMounts -}}
                {{- toYaml . | nindent 14 }}
              {{- end }}
          volumes:
            - name: youtubedl-cron-config
              persistentVolumeClaim:
                claimName: youtubedl-cron-config
            {{- range .additionalVolumes -}}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
