---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-cron-config
  annotations:
    {{ toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: {{ .Values.persistence.storageClass }}

{{ if not (or .job_download_volume .Values.download_volume) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-cron-downloads
  annotations:
    {{ toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: {{ .Values.persistence.storageClass }}
{{ end }}